namespace TheBlockProject.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulateAnswerDatabase : DbMigration
    {
        public override void Up()
        {
            Sql(@"
SET IDENTITY_INSERT [dbo].[Answers] ON
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1003, N'1 - Not at all', 6054)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1006, N'2 ', 6054)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1009, N'3', 6054)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1010, N'4', 6054)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1011, N'5 - Very accessible', 6054)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1012, N'Yes', 6055)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1013, N'No', 6055)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1014, N'Yes', 6056)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1015, N'No', 6056)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1016, N'Yes', 6057)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1017, N'No', 6057)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1018, N'1 - I have a lower bar than most people', 6059)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1019, N'2', 6059)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1021, N'3', 6059)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1022, N'4', 6059)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1023, N'5 - I can''t stand cluttered or messy spaces', 6059)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1024, N'Yes', 6058)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1025, N'No', 6058)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1026, N'1 - I am a minimalist, only essentials', 6060)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1028, N'2', 6060)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1029, N'3', 6060)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1030, N'4', 6060)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1032, N'5 - I collect lots of things; you never know when something might come in handy!', 6060)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1033, N'1 - I prefer to keep to myself', 6061)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1034, N'2', 6061)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1035, N'3', 6061)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1037, N'4', 6061)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1040, N'5 - I love interacting with my neighbors', 6061)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1041, N'Yes', 6062)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1042, N'No', 6062)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1043, N'Yes', 6067)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1045, N'No', 6067)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1046, N'Yes', 6070)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1047, N'No', 6070)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1048, N'Yes', 6073)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1049, N'No', 6073)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1050, N'7:00 PM - 9:00 PM', 6076)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1051, N'9:00 PM - 11:00 PM', 6076)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1052, N'11:00 PM - 1:00 AM', 6076)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1053, N'1:00 AM - 3:00 AM', 6076)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1054, N'5:00 AM - 7:00 AM', 6077)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1055, N'7:00 AM - 9:00 AM', 6077)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1056, N'9:00 AM - 11:00 AM', 6077)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1057, N'11:00 Am - 1:00 PM', 6077)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1058, N'I''m typically home during the day, but out and about with work or social activities at night', 6078)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1059, N'I''m typically home in the evenings and at night, but out and about with work or social activities during the day.', 6078)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1060, N'I''m home most of the time.', 6078)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1061, N'I''m rarely home.', 6078)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1062, N'I like to socialize inside my home.', 6079)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1063, N'I like to socialize outside my home.', 6079)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1064, N'I don''t have a preference.', 6079)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1065, N'1 - I am very quiet', 6090)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1067, N'2', 6090)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1068, N'3', 6090)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1069, N'4', 6090)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1070, N'5 - I am very loud', 6090)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1071, N'Yes', 6091)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1072, N'No', 6091)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1073, N'Yes', 6093)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1074, N'No', 6093)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1075, N'Yes', 6094)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1076, N'No', 6094)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1077, N'Yes', 6119)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1078, N'No', 6119)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1079, N'Yes', 6120)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1080, N'No', 6120)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1081, N'7:00 PM - 9:00 PM', 6122)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1082, N'9:00 PM - 11:00 PM', 6122)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1083, N'11:00 PM - 1:00 AM', 6122)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1084, N'1:00 AM - 3:00 AM', 6122)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1085, N'5:00 AM - 7:00 AM', 6123)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1086, N'7:00 AM - 9:00 AM', 6123)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1087, N'9:00 AM - 11:00 AM', 6123)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1088, N'11:00 AM - 1:00 PM', 6123)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1089, N'I''m typically home during the day, but out and about with work or social activities at night', 6124)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1090, N'I''m typically home in the evenings and at night, but out and about with work or social activities during the day.', 6124)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1091, N'I''m home most of the time.', 6124)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1092, N'I''m rarely home.', 6124)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1093, N'I socialize inside.', 6125)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1094, N'I socialize outside.', 6125)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1095, N'I don''t have a preference.', 6125)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1096, N'Yes', 6133)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1098, N'No', 6133)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1099, N'Yes', 6134)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1100, N'No', 6134)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1103, N'1 - I am very quiet', 6139)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1104, N'2', 6139)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1106, N'3', 6139)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1107, N'4', 6139)
INSERT INTO [dbo].[Answers] ([Id], [Text], [QuestionId]) VALUES (1108, N'5 - I am very loud', 6139)
SET IDENTITY_INSERT [dbo].[Answers] OFF

");
        }
        
        public override void Down()
        {
        }
    }
}
